/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.tattooflow.View;

import apoio.Formatacao;
import apoio.Mensagem;
import apoio.Validacao;
import com.mycompany.tattooflow.Controller.ClienteController;
import com.mycompany.tattooflow.Model.Cliente;
import apoio.PDFManager;
import java.io.IOException;
import java.util.ArrayList;

/**
 *
 * @author marcus.arenhardt
 */
public class TelaCliente extends javax.swing.JInternalFrame {

    ClienteController c = new ClienteController();
    private int idEditando = -1; // -1 significa que não está editando

    /**
     * Creates new form TelaClientes
     */
    public TelaCliente() {
        initComponents();
        montaTabela();
        Formatacao.formatarCpf(txtCpfCli);
        Formatacao.formatarTelefone(txtCelularCli);
        Formatacao.formatarData(txtDataNasc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bntSalvarCli = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtNomeCli = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtCpfCli = new javax.swing.JFormattedTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtCelularCli = new javax.swing.JFormattedTextField();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtEmailCli1 = new javax.swing.JTextPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        txtDataNasc = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bntVisualizarCli = new javax.swing.JButton();
        bntExcluirCli = new javax.swing.JButton();
        bntEditar = new javax.swing.JButton();
        bntPDF = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setText("Nome:");

        jLabel2.setText("CPF:");

        jLabel3.setText("Email:");

        jLabel4.setText("Celula:");

        jLabel5.setText("Data de Nascimento:");

        bntSalvarCli.setText("Salvar");
        bntSalvarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalvarCliActionPerformed(evt);
            }
        });

        jScrollPane7.setViewportView(txtNomeCli);

        jScrollPane8.setViewportView(txtCpfCli);

        jScrollPane9.setViewportView(txtCelularCli);

        jScrollPane10.setViewportView(txtEmailCli1);

        jScrollPane11.setViewportView(txtDataNasc);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bntSalvarCli))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(bntSalvarCli))
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(173, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro", jPanel1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        bntVisualizarCli.setText("Visualizar");

        bntExcluirCli.setText("Excluir");
        bntExcluirCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExcluirCliActionPerformed(evt);
            }
        });

        bntEditar.setText("Editar");
        bntEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEditarActionPerformed(evt);
            }
        });

        bntPDF.setText("Gerar PDF");
        bntPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bntVisualizarCli)
                    .addComponent(bntExcluirCli)
                    .addComponent(bntEditar)
                    .addComponent(bntPDF))
                .addGap(38, 38, 38))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(bntVisualizarCli)
                        .addGap(18, 18, 18)
                        .addComponent(bntExcluirCli)
                        .addGap(18, 18, 18)
                        .addComponent(bntEditar)
                        .addGap(18, 18, 18)
                        .addComponent(bntPDF)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Visualização", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntSalvarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalvarCliActionPerformed
        if (txtNomeCli.getText().trim().isEmpty() || txtEmailCli1.getText().trim().isEmpty()) {
            Mensagem.aviso("Preencha todos os campos obrigatórios!");
            return;
        }
        String cpfLimpo = Formatacao.removerFormatacao(txtCpfCli.getText()).trim();
        if (cpfLimpo.isEmpty()) {
            Mensagem.aviso("Preencha o CPF!");
            return;
        }
        if (!Validacao.validarCPF(cpfLimpo)) {
            Mensagem.aviso("CPF inválido!");
            return;
        }
        Cliente cli = new Cliente();
        cli.setNome(txtNomeCli.getText());
        cli.setCpf(txtCpfCli.getText());
        cli.setEmail(txtEmailCli1.getText());
        cli.setCelular(txtCelularCli.getText());
        cli.setData_nasc(txtDataNasc.getText());

        boolean retorno;

        if (idEditando != -1) {
            // Está editando
            cli.setId(idEditando);
            retorno = c.editar(cli);
            idEditando = -1; // reseta após editar
        } else {
            // Está salvando novo
            retorno = c.salvar(cli);
        }

        if (retorno) {
            txtNomeCli.setText("");
            txtCpfCli.setText("");
            txtEmailCli1.setText("");
            txtCelularCli.setText("");
            txtDataNasc.setText("");
            txtNomeCli.requestFocus();
            montaTabela();
        }


    }//GEN-LAST:event_bntSalvarCliActionPerformed

    private void bntExcluirCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluirCliActionPerformed
        String idString = String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 0));
        int id = Integer.parseInt(idString);
        boolean retorno = c.excluir(id);
        if (retorno) {
            montaTabela();
        }
    }//GEN-LAST:event_bntExcluirCliActionPerformed

    private void bntEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEditarActionPerformed
        int linhaSelecionada = jTable1.getSelectedRow();

        if (linhaSelecionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione um cliente para editar!", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Pega os dados da linha selecionada e preenche os campos
        txtNomeCli.setText(String.valueOf(jTable1.getValueAt(linhaSelecionada, 1)));
        txtCpfCli.setText(String.valueOf(jTable1.getValueAt(linhaSelecionada, 2)));
        txtEmailCli1.setText(String.valueOf(jTable1.getValueAt(linhaSelecionada, 3)));
        txtCelularCli.setText(String.valueOf(jTable1.getValueAt(linhaSelecionada, 4)));
        txtDataNasc.setText(String.valueOf(jTable1.getValueAt(linhaSelecionada, 5)));

        // Guarda o ID e troca para a aba de cadastro
        idEditando = Integer.parseInt(String.valueOf(jTable1.getValueAt(linhaSelecionada, 0)));
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_bntEditarActionPerformed

    private void bntPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPDFActionPerformed
        ArrayList<Cliente> lista = c.recuperarTodos();
        try {
            PDFManager.gerar(lista, "clientes.pdf");
            Mensagem.informacao("PDF gerado: clientes.pdf");
        } catch (IOException ex) {
            Mensagem.erro("Erro ao gerar PDF: " + ex.getMessage());
        }
    }//GEN-LAST:event_bntPDFActionPerformed

    private void montaTabela() {
        ArrayList<Cliente> clientes = c.recuperarTodos();
        if (clientes == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ocorreu um erro ao consultar os clientes", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
        } else {
            jTable1.setModel(new javax.swing.table.AbstractTableModel() {
                @Override
                public String getColumnName(int column) {
                    switch (column) {
                        case 0:
                            return "ID";
                        case 1:
                            return "Nome";
                        case 2:
                            return "CPF";
                        case 3:
                            return "Email";
                        case 4:
                            return "Celular";
                        case 5:
                            return "Data de Nasc.";
                        default:
                            return "";
                    }
                }

                @Override
                public int getColumnCount() {
                    return 6;
                }

                @Override
                public int getRowCount() {
                    return clientes.size();
                }

                @Override
                public Object getValueAt(int rowIndex, int columnIndex) {
                    Cliente cli = clientes.get(rowIndex);

                    if (cli != null) {
                        switch (columnIndex) {
                            case 0:
                                return cli.getId();
                            case 1:
                                return cli.getNome();
                            case 2:
                                return cli.getCpf();
                            case 3:
                                return cli.getEmail();
                            case 4:
                                return cli.getCelular();
                            case 5:
                                return cli.getData_nasc();
                        }
                    }

                    return "n/d";
                }
            });

            jTable1.getColumnModel().getColumn(0).setMinWidth(40);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(60);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntEditar;
    private javax.swing.JButton bntExcluirCli;
    private javax.swing.JButton bntPDF;
    private javax.swing.JButton bntSalvarCli;
    private javax.swing.JButton bntVisualizarCli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JFormattedTextField txtCelularCli;
    private javax.swing.JFormattedTextField txtCpfCli;
    private javax.swing.JFormattedTextField txtDataNasc;
    private javax.swing.JTextPane txtEmailCli1;
    private javax.swing.JTextPane txtNomeCli;
    // End of variables declaration//GEN-END:variables

}
