/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tattooflow.View;

/**
 *
 * @author marcus.arenhardt
 */
public class TelaInicial extends javax.swing.JFrame {
    TelaCliente tc;
    TelaTatuador tt;
    TelaTatuagem tg;
    TelaEstilos ts;
    TelaSessao tss;

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        DskPainel = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuClientes = new javax.swing.JMenuItem();
        MenuTatuadores = new javax.swing.JMenuItem();
        MenuTatuagens = new javax.swing.JMenuItem();
        MenuEstilos = new javax.swing.JMenuItem();
        MenuSessao = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout DskPainelLayout = new javax.swing.GroupLayout(DskPainel);
        DskPainel.setLayout(DskPainelLayout);
        DskPainelLayout.setHorizontalGroup(
            DskPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        DskPainelLayout.setVerticalGroup(
            DskPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMenu1.setText("Cadastrar");

        MenuClientes.setText("Clientes ");
        MenuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuClientesActionPerformed(evt);
            }
        });
        jMenu1.add(MenuClientes);

        MenuTatuadores.setText("Tatuadores");
        MenuTatuadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuTatuadoresActionPerformed(evt);
            }
        });
        jMenu1.add(MenuTatuadores);

        MenuTatuagens.setText("Tatuagens");
        MenuTatuagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuTatuagensActionPerformed(evt);
            }
        });
        jMenu1.add(MenuTatuagens);

        MenuEstilos.setText("Estilos");
        MenuEstilos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEstilosActionPerformed(evt);
            }
        });
        jMenu1.add(MenuEstilos);

        MenuSessao.setText("Sessão");
        MenuSessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSessaoActionPerformed(evt);
            }
        });
        jMenu1.add(MenuSessao);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DskPainel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DskPainel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuTatuadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuTatuadoresActionPerformed
       
        if (tt == null || tt.isClosed()){
            tt = new TelaTatuador();
            tt.setVisible(true);
            DskPainel.add(tt);
        }
    }//GEN-LAST:event_MenuTatuadoresActionPerformed

    private void MenuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuClientesActionPerformed
        
        if (tc == null || tc.isClosed()){
            tc = new TelaCliente();
            tc.setVisible(true);
            DskPainel.add(tc);
        }
            
    }//GEN-LAST:event_MenuClientesActionPerformed

    private void MenuTatuagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuTatuagensActionPerformed
       
        if (tg == null || tg.isClosed()){
            tg = new TelaTatuagem();
            tg.setVisible(true);
            DskPainel.add(tg);
        }
    }//GEN-LAST:event_MenuTatuagensActionPerformed

    private void MenuEstilosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEstilosActionPerformed
        
        if (ts == null || ts.isClosed()){
            ts = new TelaEstilos();
            ts.setVisible(true);
            DskPainel.add(ts);
        }
    }//GEN-LAST:event_MenuEstilosActionPerformed

    private void MenuSessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSessaoActionPerformed
        
        if (tss == null || tss.isClosed()){
            tss = new TelaSessao();
            tss.setVisible(true);
            DskPainel.add(tss);
        }
    }//GEN-LAST:event_MenuSessaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DskPainel;
    private javax.swing.JMenuItem MenuClientes;
    private javax.swing.JMenuItem MenuEstilos;
    private javax.swing.JMenuItem MenuSessao;
    private javax.swing.JMenuItem MenuTatuadores;
    private javax.swing.JMenuItem MenuTatuagens;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
